middle 1回目
giangtkdhy/Dojo_kadai pull request #16
Opened 2023-06-27 23:22 UTC by giangtkdhy

中間課題はここになります。よろしくお願いします！

2023-06-28 01:24 UTC, natsukiyamada commented on middle/middle.html
> +          return "category-1";
以下修正お願いします~

`category-1`とかだとちょっと分かりにくいので、変数から何のカテゴリーか分かるような
命名にしてほしいです！

2023-06-28 01:33 UTC, natsukiyamada commented on middle/middle.html
> +          ? category.toString().toLowerCase()
たぶん`toString().toLowerCase()`をつけなくても動く気がします..
（`toString().toLowerCase()`を使った理由などあれば教えてください~）

2023-06-28 01:51 UTC, natsukiyamada commented on middle/middle.html
> +            categoryCell.className = getCategoryClass(
以下提案です！

36行目の処理について、
`news.label.value`を使えばシンプルに実装できそうだなと思いました！

今している処理って、
categoryがあれば自分で作成したクラス名を返す関数を作って
 categoryCellにそのクラスを追加する処理になっていると思いますが、
`news.label.value`で取得できるデータは、実質categoryの英語表記なので、そのままcategoryCell.classNameに突っ込めると思います~

2023-06-28 01:57 UTC, natsukiyamada commented on middle/middle.html
> +      document.addEventListener("DOMContentLoaded", async () => {
以下修正提案です！

特段必要なければaddEventListenerを使わないで実装できると思います！

スクリプトタグはファイルの最後に位置している（すべてのHTMLがパース（解析）され、すべてのDOM要素が利用可能になった後にスクリプトが実行される）ので、addEventListenerを使ってDOMが読み込まれるまで待つ必要はないと思いました！

2023-06-28 02:18 UTC, natsukiyamada commented on middle/middle.html
> +            dateCell.textContent = news.day && news.day.value;
以下修正お願いします~


31行目の`news.day && news.day.value;`、
35行目の`news.category && news.category.value;`
42行目の`news.content && news.content.value;`
48行目の`news.link && news.link.value;`

上記の部分のコードについてですが、
それぞれデータがなければそもそもテーブルを作成できないので、
コードの最初の方で、それぞれデータがあるかどうか一括で確認するのがいいかなと思います。
以下のようなイメージです。
```
//25行目あたりで以下のように存在するかチェックする
if( !news.day ) {
  window.alert()
   return 
}

// 他のデータも同じようにやる

```

2023-06-28 02:23 UTC, natsukiyamada requested changes
レビューしました！お時間ある際に確認おねがいします！

2023-06-28 04:38 UTC, giangtkdhy commented on middle/middle.html
> +          ? category.toString().toLowerCase()
確かに、なくてもいけました。課題やる時、CSS上手くいけないので、大文字と小文字の問題と思って、入れてみただけです。

2023-06-28 08:04 UTC, natsukiyamada commented on middle/middle.html
> +            titleLink.href = news.link;
以下修正お願いします~

59行目で遷移先のリンクに飛べないので修正お願いします！
たぶん`news.link`プロパティはなかった気がします。

2023-06-28 08:09 UTC, natsukiyamada commented on middle/middle.html
> +        return "";
以下修正お願いします！

79行目は必要なさそうです！

2023-06-28 08:16 UTC, natsukiyamada commented on middle/middle.html
> +            categoryCell.classList.add(getCategoryClass(news.category.value));
以下修正提案です！

news.label.valueはnews.category.valueに対応している、かつ英語表記なので
```
categoryCell.className  = news.label.value
```

だとシンプルに実装できると思います。
こうすると各タグのクラス名は `class="product"`（カテゴリーに応じたlabelがクラス名になる）という感じになると思うので、
後はcssファイルで productというクラスに対してCSSを当てたら簡単に実装できます。
なのでetCategoryClass関数を定義する必要もなくなります。

※ちょっとよく分からない...みたいな場合は聞いてください！

2023-06-28 08:24 UTC, natsukiyamada commented on middle/middle.html
> +        .then((response) => {
以下補足です！

現在の処理だと、
axios().then()の中で全ての処理を行っているので、できれば処理を分けてほしいんですよね..

例えば、
①必要なデータがそろっているかチェックする関数
② タイトルが30文字を超える場合は省略表示する関数 等です。

処理を分けていくとコードの変更もかなり多くなるので、余力がもしあればコードの分割なども
したいところです。（おそらく余裕はないかなと思うので念頭にだけ置いておいてください...）

2023-06-28 08:27 UTC, natsukiyamada requested changes
レビューしました！確認お願いします！

2023-06-29 00:25 UTC, natsukiyamada commented on middle/middle.html
> +      }
以下修正お願いします！

async, awaitをつけてください~
```
async function getData() {
        return await axios.get(
          "https://54o76ppvn8.execute-api.ap-northeast-1.amazonaws.com/prod/bb-dojo",
          {
            params: { id: "dojo", query: "order by day desc limit 3" },
          }
        );
      }
```

2023-06-29 00:39 UTC, natsukiyamada commented on middle/middle.html
> +        }
以下修正の提案です！

ここも関数化すると再利用性が高まりますね！
関数化してみましょう。

2023-06-29 00:39 UTC, natsukiyamada requested changes
単一の処理ごとに関数化されていててわかりやすいですね！全体的にいい感じだと思います！
一部修正お願いします~

2023-06-29 05:58 UTC, natsukiyamada approved these changes
内容OKです！ おつかれさまでした～

2023-06-29 05:58 UTC, merged