Jsapinew
giangtkdhy/Dojo_kadai pull request #9
Opened 2023-06-21 04:57 UTC by giangtkdhy

これで最新です。check お願いします。

2023-06-21 10:11 UTC, natsukiyamada commented on JSAPI/JSAPI_2.js
> +  var products = {
以下修正お願いします！

`var`ではなく`const`で変数宣言してください~
他の箇所も同様にして修正お願いします！

2023-06-21 10:42 UTC, natsukiyamada commented on JSAPI/JSAPI_2.js
> +  }
以下修正お願いします！

今回はdayjsではなくdate-fnsを使用するように指定されているので、
date-fnsを使うようにしてください！

2023-06-21 10:47 UTC, natsukiyamada commented on JSAPI/JSAPI_2.js
> +      });
以下修正お願いします！

今課題はJavaScript APIを使用した実装を想定しているので、
REST APIは使用しないで実装していただくようお願いします！
※REST API→41行目以降の`kintone.api(...)`の部分を指しています

2023-06-21 10:49 UTC, natsukiyamada commented on JSAPI/JSAPI_2.js
> +  ], function(event) {
以下追記お願いします！

課題の要件を見ると、
> 挿⼊先の⽂字列フィールドは常に編集不可にしておきたい

と記載されています。なので上記フィールドは編集不可になるようにJavaScriptで実装してください~

2023-06-21 10:54 UTC, natsukiyamada requested changes
レビューしたのでご確認お願いします！

また、以下の要件を満たすように実装お願いいたします！

①日付操作には`date-fns`を使用する
②重複禁止項目_⽂字列フィールドは常に編集不可にする_
③サイボウズ製品フィールド、管理番号フィールドに値が入ったタイミングで、
重複禁止項目_⽂字列フィールドに自動で値が挿入されるようにする。

2023-06-22 06:30 UTC, natsukiyamada commented on JSAPI/JSAPI_2.js
> +})();
イベントごとに役割が分離されていて分かりやすいです！良いと思いました！

2023-06-22 06:38 UTC, natsukiyamada commented on JSAPI/JSAPI_2.js
> +  }
以下修正判断お任せします！

formatDate関数に関してですが、中身を見ると
dateFns.format関数を返しているだけなので、
formatDate()としてdateFns.format()をラップしなくてもいいかな~と思いました。
なので特段理由なければ、19行目に直接dateFns.format(date, "YYYYMMDD");と記載してもらっていいと思います！

ライブラリの関数をラップした新しい関数を定義する場合は、
その新しい関数で何らかの追加の処理を行ったり、機能を拡張したりすることが一般的です。
以下のようなイメージです。
```
function formatDate(date) {
   ~何か他の処理~
   ~何か他の処理~
   const  formattedDate = 他の処理で成形されたデータ
   return dateFns.format(formattedDate, "YYYYMMDD");
  }
```

2023-06-23 01:09 UTC, Eain99 commented on JSAPI/JSAPI_1.js
お疲れ様です。
課題6-1は即時関数使わないといけないというルールがあるので、即時関数を使いましょう。
宜しくお願いします！

2023-06-26 08:24 UTC, Eain99 commented on JSAPI/JSAPI_1.js
> +          '課題': { type: 'SINGLE_LINE_TEXT', value: '' }
コード自体は大丈夫です！
細かいことなんですが、
10、11、12 行目: '{'の後にスペースは不要です、'}'の前のスペースも不要です。
他の場所のインデントも確認していただければと思います。

2023-06-28 09:05 UTC, Eain99 commented on JSAPI/JSAPI_1.js
> +          '課題': { type: 'SINGLE_LINE_TEXT', value: '' }
@giangtkdhy 
お疲れ様です。
こちらは修正済みでしょうか。
宜しくお願いします！

2023-07-03 08:27 UTC, giangtkdhy commented on JSAPI/JSAPI_1.js
> +          '課題': { type: 'SINGLE_LINE_TEXT', value: '' }
遅くなって、申し訳ないです。通知気づいてなかったです。

2023-07-05 07:26 UTC, Eain99 commented
修正ありがとうございます。
レビューOKです

2023-07-05 07:26 UTC, merged